version: "3.7"
services:
  # dart-pad:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-dart-pad
  #   networks:
  #     - nginx-proxy
  #   ports:
  #     - "8000"
  #   entrypoint: bash -c "cd /dart-pad && DARTPAD_BACKEND=http://dart-services.api.ynu.edu.cn grind serve-custom-backend"

  dart-services:
    build:
      context: dart-services
      dockerfile: cloud_run.Dockerfile
    # networks:
    #   - nginx-proxy
    ports:
      - "8082:8082"
      - "8080:8080"
    # volumes:
    #   - ./dart-services:/dart-services
    # entrypoint: bash -c "cd /dart-services && pub get && dart bin/server_dev.dart --port 8082"

# networks:
#   nginx-proxy:
#     external:
#       name: nginx-proxy-default