apiVersion: v1
data:
  hotreload.sh: |-
    #!/bin/bash

    while true
    do
        find /app/lib/ -name '*.dart' | entr -dnp /scripts/hotreloader.sh /_
    done
  hotreloader.sh: "#!/bin/bash\n\nset -euo pipefail \nif [[ \"${1-}\" != \"\" ]];
    then \n    echo $1 \n    if [[ \"$1\" =~ \\/state\\/ || \"$1\" =~ backend ]];
    then \n        echo \"Restarting\" \n        tmux send-keys -t webSession.0 R
    \n    else \n        echo \"Reloading\" \n        tmux send-keys -t webSession.0
    R \n    fi \nfi"
  startup.sh: |-
    #!/bin/bash

    tmux new -d -s webSession

    tmux send-keys -t webSession.0 "(cd /app && /usr/local/flutter/bin/flutter build web &&  /usr/local/flutter/bin/flutter run --web-port 5000 -d web-server --web-hostname 0.0.0.0)" ENTER

    tmux new -d -s webReloader

    tmux send-keys -t webReloader.0 "sh /scripts/hotreload.sh" ENTER
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: preview-scripts
