apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: default
spec:
  containers:
  - image: nicolaka/netshoot:latest
    command: ['sleep', '3600']
    imagePullPolicy: IfNotPresent
    name: netshoot
  restartPolicy: Always