---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __DOMAIN__
  namespace: __NAMESPACE__
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache static-cache;
      proxy_cache_valid any 60m;
      add_header X-Cache-Status $upstream_cache_status;
spec:
  rules:
  - host: __DOMAIN__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: __DOMAIN__
            port:
              number: 80
  ingressClassName: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: __DOMAIN__
  namespace: __NAMESPACE__
  labels:
    app: __PODID__
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: __PODID__