apiVersion: v1
kind: Service
metadata:
  name: __SVCNAME__
  namespace: __NAMESPACE__
  labels:
    app: __PODID__
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: __PODID__